name = "AirspeedVelocity_ManifestTest"
uuid = "b4813b32-ecad-4dab-98c7-099a8582f3f3"
authors = ["Zentrik <Zentrik@users.noreply.github.com>"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
